# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ada962613fe24090b2c6a9a36963e797"
name = "Popup Builder"
application_url = "https://pop-up-builder-five.vercel.app/app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "https://pop-up-builder-five.vercel.app/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://pop-up-builder-five.vercel.app/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://pop-up-builder-five.vercel.app/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_metaobject_definitions,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = [
  "https://pop-up-builder-five.vercel.app/auth/callback",
  "https://pop-up-builder-five.vercel.app/auth/shopify/callback",
  "https://pop-up-builder-five.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://pop-up-builder-five.vercel.app/api/storefront"
subpath = "popup-builder"
prefix = "apps"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[events]
api_version = "unstable"

  [[events.subscription]]
  handle = "dummy-event"
  topic = "Product"
  actions = ["create"]
  uri = "/webhooks/dummy"
